<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
	<meta name="description" content="best hotel on interstate 70 in kansas">
	<meta name="viewport" content="width=devices-width, initial-scale=1">
	<link rel="stylesheet" href="hotelstyle.css">
	<link rel="stylesheet" href="slider.css">
	<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<title><?php echo $page_title; ?></title>
</head>
<body>
	<a href = "home.php"><img id = "logo" src = "likestayhotel.jpg" alt = "Like stay hotel logo"></a>
		<span id = "phone">PH: 1(800) 123-4567</span>
		<nav>
	<ul>
		<li><a href="home.php">Home</a></li>
		<li><a href="reservation.php">Reservation</a></li>
		<li><a href="testimonials.php">Testimonials</a></li>
		<li><a href="about.php">About</a></li>
	</ul>
</nav>
	